name: Deploy Amplify Functions on main

on:
  push:
    branches:
      - master 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set AWS Credentials and Configuration
        run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Initialize Amplify
        run: amplify init --appId d39dspc9b1g2w --envName main --region us-east-1 --yes

      - name: Deploy Amplify Backend
        run: amplify push --yes --simple

        env:
          AMPLIFY_ENV: main
          CI: true
